services:
  techsupport_app:
    container_name: techsupport_app
    build:
      context: .               # <- 현재 폴더를 빌드 컨텍스트로
      dockerfile: dockerfile   # <- 파일명이 'dockerfile'인 경우 반드시 지정
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/naiz.db   # <-- 너의 실제 DB 위치
      - MANUALS_DIR=/app/uploads/manuals
      - TZ=Asia/Seoul
    volumes:
      - ./:/app               # 앱 코드
      - ./uploads:/app/uploads
      - ./data:/app/data