INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (10,'경기 안성시청','경기도 안성시 시청길 25',NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (11,'경기 의왕시청','경기도 의왕시 시청로 11',NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (12,'경기 광주시청 재난','경기도 광주시 행정타운로 50',NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (13,'경기도청','경기도 수원시 영통구 도청로 30',NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (14,'세종정부청사','세종특별자치시 다솜2로 94',NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (15,'정부과천청사','경기도 과천시 관문로 47',NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (16,'충남 쳥양군청','충청남도 청양군 청양읍 문화예술로 222',NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (17,'산청군청','경상남도 산청군 산청읍 산엔청로 1',NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (18,'전북 남원시청','전북특별자치도 남원시 시청로 60',NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (19,'전북 영광군청','전라남도 영광군 영광읍 중앙로 203',NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 서울교통공사본사','서울특별시 성동구 천호대로 346',NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 방화',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 개화산',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 김포공항',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 송정',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 마곡',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 발산',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 우장산',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 화곡',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 까치산',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 신정',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 목동',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 오목교',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 양평',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 영등포구청',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 영등포시장',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 신길',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 여의도',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 여의나루',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 마포',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 공덕',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 애오개',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 충정로',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 서대문',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 광화문',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 종로3가',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 을지로4가',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 동대문역사문화공원',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 청구',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 신금호',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 행당',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 왕십리',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 마장',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 답십리',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 장한평',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 군자',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 아차산',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 광나루',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 천호',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 강동',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 둔촌동',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 길동',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 올림픽공원',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 굽은다리',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 명일',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 방이',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 고덕',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 오금',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 상일동',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 개롱',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 거여',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (20,'5호선 마천',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (21,'Sk하이닉스_이천','경기도 이천시 부발읍 경충대로 2091',NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (22,'Sk하이닉스_청주',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (23,'Sk하이닉스_분당',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (24,'Sk하이닉스_서울 센터원',NULL,NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (25,'현대 트랜시스_서산','충남 서산시 성연면 신당1로 105',NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (26,'세종 재난안전센터','세종 도움6로 42',NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (27,'부산 국도관리청','부산 동구 초량중로 67',NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (28,'농어촌공사 경북본부','대구광역시 북구 구암로 158',NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (29,'에스오일 마곡','서울 강서구 방화대로 254',NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (30,'경북바이오벤쳐프라자_안동','경상북도 안동시 풍산읍 산업단지길 88',NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (31,'CJ한국복합물류센터','경기 군포시 번영로 82',NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (32,'제주특별자치도개발공사','제주특별자치도 제주시 조천읍 남조로 1717-35',NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (33,'서울 동작종합정보센터','서울특별시 동작구 여의대방로 74',NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (35,'한국식품연구원_전주','전북 완주군 이서면 농생명로 245',NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (37,'경주 풍산 안강 사업소','경상북도 경주시 안강읍 안현로 1294-42',NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (38,'대전 군수사령부','대전광역시 유성구 반석동 704',NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (41,'서울 성동도로사업소','서울특별시 성동구 자동차시장길 41 성동도로교통사업소',NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (42,'서울 마포문화비축기지','서울특별시 마포구 증산로 87',NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (43,'대전광역시 공원관리사업소','대전 중구 사정동 산1-6',NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (44,'한국환경산업기술원','서울특별시 은평구 진흥로 215 한국환경산업기술원',NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (45,'서울시설공단','서울특별시 성동구 청계천로 540',NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (46,'충북 도로관리사업소','충청북도 청주시 청원구 내수읍 초정약수로 362-16',NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (47,'인천 환경산업연구단지','인천 서구 정서진로 410',NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (48,'충청북도경찰청 교통정보센터','충북 청주시 청원구 2순환로 168',NULL,NULL,NULL,datetime('now','localtime'));
INSERT OR IGNORE INTO site_locations (site_id, name, address, manager_name, manager_phone, note, created_at) VALUES (49,'국토교통부 대전지방국토관리청','대전광역시 동구 계족로 447 대전지방국토관리청',NULL,NULL,NULL,datetime('now','localtime'));