INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('서울 강남구청',8445,24,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('서울 송파구청',968,1,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('서울 성동구청',4720,8,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('서울 종로구청',3027,5,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('서울 서대문구청',1787,3,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('서울 성복구청',4300,5,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('청주시청',9300,14,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('경기 부천시청',9000,14,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('경기 파주시청',7200,12,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('경기 안성시청',4700,6,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('경기 의왕시청',2496,7,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('경기 광주시청 재난',225,1,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('경기도청',5156,37,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('세종정부청사',2478,9,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('정부과천청사',217,1,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('충남 쳥양군청',1426,5,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('산청군청',2400,8,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('전북 남원시청',948,2,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('전북 영광군청',101,1,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('서울 지하철 5호선 스마트스테이션',7552,118,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('Sk하이닉스_이천',4100,17,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('Sk하이닉스_청주',2150,12,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('Sk하이닉스_분당',454,2,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('Sk하이닉스_서울 센터원',30,2,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('현대 트랜시스_서산',140,1,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('세종 재난안전센터',453,1,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('부산 국도관리청',1764,13,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('농어촌공사 경북본부',896,6,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('에스오일 마곡',400,1,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('경북바이오벤쳐프라자_안동',287,5,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('CJ한국복합물류센터',268,1,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('재주특별자치도개발공사',266,1,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('서울 동작종합정보센터',250,1,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('판교제로시티 자율주행',206,2,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('한국식품연구원_전주',200,1,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('상주 영천 고속도로',160,3,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('경주 풍산 안강 사업소',156,3,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('대전 군수사령부',130,3,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('대전광역시 서구',130,1,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('광양 우회도로',100,10,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('서울 성동도로사업소',85,1,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('서울 마포문화비축기지',80,2,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('대전광역시 공원관리사업소',60,1,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('한국환경산업기술원',54,2,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('서울시설공단',370,2,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('충북 도로관리사업소',107,2,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('인천 환경산업연구단지',120,1,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('충청북도경찰청 교통정보센터',82,1,NULL,datetime('now','localtime'),datetime('now','localtime'));
INSERT OR IGNORE INTO sites (name, camera_count, nrs_count, note, created_at, updated_at) VALUES ('국토교통부 대전지방국토관리청',12,1,NULL,datetime('now','localtime'),datetime('now','localtime'));
